name: Build Hub runner

on:
  push:
    branches: ['main']
    paths:
    - runner/*
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/sprint-cloud/runner
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_CONTEXT: runner
  DOCKER_BUILDKIT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        run: |-
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest $IMAGE_CONTEXT
      - name: Test Image
        run: |-
          docker run $IMAGE_NAME:$IMAGE_TAG sh -c 'echo Very simple test' 
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/sprint-cloud
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Push image
        run: |-
          docker push -a $IMAGE_NAME
          # docker push $IMAGE_NAME:latest
        
